### ISSUE TITLE
Xcode 13 + macOS Monterey 12.0 编译报错(objc4-818.2)

### ISSUE THREAD

**Issue by zhenhuamu** [LGCooci/KCCbjc4_debug#20]
Assertion failed: (sel_registerName(sel_getName(meth.name())) == meth.name()), function methodizeClass, file /Users/mu/Desktop/KCCbjc4_debug-master/objc4-818.2/runtime/objc-runtime-new.mm, line 1536.

**Comment by LGCooci** [comment]
macOS Monterey 12.0 还不是系统正式版本 所以无法做到绝对的兼容! 我会在正式版本发布 第一时间更新

**Comment by LGCooci** [comment]
这个要看苹果开源 时间还不好说
