### ISSUE TITLE
_sel_hash

### ISSUE THREAD

**Issue by xiuxinkexin** [LGCooci/KCCbjc4_debug#22]
dyld: Symbol not found: _sel_hash
  Referenced from: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  Expected in: /Users/xiuxin/Library/Developer/Xcode/DerivedData/objc-bwlfwhghsmulfudmcqtfprllhkut/Build/Products/Debug/libobjc.A.dylib
 in /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
 有人碰到过这个错误吗

**Comment by LGCooci** [comment]
Xcode 13.1 需等objc824
