### ISSUE TITLE
xcode13下奔溃

### ISSUE THREAD

**Issue by MrBMask** [LGCooci/KCCbjc4_debug#23]
Assertion failed: (sel_registerName(sel_getName(meth.name())) == meth.name()), function methodizeClass, file objc-runtime-new.mm, line 1536.
warning: could not find Objective-C class data in the process. This may reduce the quality of type information available.
(lldb)

**Comment by LGCooci** [comment]
靓仔靓女 因为系统更新原因 需要等待 824源码更新

**Comment by Jentlezhi** [comment]
824什么时候更新呢？

**Comment by faimin** [comment]
> 824什么时候更新呢？

订阅下官方仓库 [https://github.com/apple-oss-distributions/objc4](https://github.com/apple-oss-distributions/objc4) 的动态，一更新你就知道了
