### ISSUE TITLE
怎么查看当前iOS或者mac os sdk使用的oc语言版本？

### ISSUE THREAD

**Issue by jackleemeta** [LGCooci/KCCbjc4_debug#24]

**Comment by LGCooci** [comment]
Objective-C 2.0 - Modern Versions
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtVersionsPlatforms.html#//apple_ref/doc/uid/TP40008048-CH106-SW1
一般人少去纠结这个版本的 可能你应该是关注的 libobjc 库的版本 我现在更新到818  正在策划 824
