### ISSUE TITLE
无法进入断点

### ISSUE THREAD

**Issue by littlechaochao** [LGCooci/KCCbjc4_debug#29]
KCObjcBuild[80175:963663] Hello, World! KCObjcBuild was compiled with optimization - stepping may behave oddly; variables may not be available.

目前无法正确的使用断点，感觉整个是乱的，查过相关配置，是debug模式，并且优化等级为None

Mac 系统 12.0.1 Xcode版本13.2.1

**Comment by LGCooci** [comment]
KC 重磅提示 调试工程很重要 源码直观就是爽
 ⚠️编译调试不能过: 请你检查以下几小点⚠️
 ①: 编译 targets 选择: KCObjcBuild
 ②: enable hardened runtime -> NO
 ③: build phase -> denpendenice -> objc
 ④: team 选择 None
 iOS进阶内容重磅分享 微信认准: KC_Cooci 麻烦来一个 👍

**Comment by songhongkang** [comment]
@littlechaochao  解决了吗？我也是进不去断点

**Comment by LGCooci** [comment]
如果你们调试还是进不去 直接微信我: KCCooci
