### ISSUE TITLE
objc4-818.2 在MaxOS 12.2.1  运行奔溃:

### ISSUE THREAD

**Issue by l770826421** [LGCooci/KCCbjc4_debug#30]
objc4-818.2 在MaxOS 12.2.1  运行奔溃:
Assertion failed: (sel_registerName(sel_getName(meth.name())) == meth.name()), function methodizeClass, file objc-runtime-new.mm, line 1536.
请问博主如何解决?

**Comment by xieliying** [comment]
同遇到此问题，macOS 12.3，Intel 芯片笔记本。

**Comment by LGCooci** [comment]
818.2 已经过时 升级到了12的系统 那就需要更新到 838源码  github 有更新 请及时clone
