### ISSUE TITLE
m1 pro 还是奔溃哦

### ISSUE THREAD

**Issue by forestfsl** [LGCooci/KCCbjc4_debug#32]
我看是支持了m1,但是在m1 电脑上面依然还是会奔溃哦

**Comment by LGCooci** [comment]
已经支持了M1哦  你的奔溃堆栈显示是什么  方便截图?

**Comment by LGCooci** [comment]
奔溃 你方便提供奔溃信息? 我好方便调试 查看原因 如果你这里不方便 WX: KC_Cooci
