### ISSUE TITLE
Unexpected character <U+1F92F> at objc-runtime-new.h for 838 & 841

### ISSUE THREAD

**Issue by Yannmm** [LGCooci/KCCbjc4_debug#33]
First thank you for providing this debug version of  objc runtime.

OS version: Monterey 12.5.1
MacBook Pro (Retina, 13-inch, Early 2015)
Processor 2.7 GHz Dual-Core Intel Core i5

Xcode Version 14.0.1 (14A400)

Build error is `Unexpected character <U+1F92F>`, which is the 🤯 symbol, as below pictures shows.

I tried to replace that symbol with some random integer, but it will cause dyld throw exception at runtime.

Any help is appreciated.

![compile error](https://user-images.githubusercontent.com/13806962/195964237-c0e933f2-6d5a-465f-8d32-821169265ff5.jpg)

**Comment by sevenuncler** [comment]
+1

**Comment by Yannmm** [comment]
Find a solution myself 😄. Here's a step by step guide:

1. download the latest version of this repo and find `objc4-866.9` open it.
2. if you compile the `objc` target it will compile successfully. But when try to run the debug target, it will crash. It's OK, all you need is search globally `sharedCacheRelativeMethodBase` and find the file defining it, which is `objc-magicsel.m`;
3. Copy the file and put it in the runtime folder of `objc4-841` project, making sure it's included in the target of `objc`;
4. Put `extern "C" uintptr_t sharedCacheRelativeMethodBase();` in your `objc-runtime-new.h` file, we are gonna replace the old method with our new one. I put it at the line 566.
5. Comment out the old definition at line 809.
6. Compile and enjoy. 🍺
